/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.sensetime.nebula.webapi4j

import com.sensetime.nebula.webapi4j.lib.*
import kotlinx.coroutines.*
import kotlin.test.Test
import kotlin.test.assertTrue

class AuthTest {

    private var serverUrl: String = System.getProperty("serverUrl")
    private var username: String = System.getProperty("username")
    private var password: String = System.getProperty("password")
    private val request: RemoteDataSource = WebApi(serverUrl, username, password).getEndpoint()
    private val unixMillisTime_2017_07_14 = 1500000000000

    @Test
    fun `test get token use wrong username password`(): Unit = runBlocking {
        request.authLogin(body = RequestAuth(username, password+"alksdjfkljadls;", 1)).map { assert(false) }.mapError { assert(true) }
    }

    @Test
    fun `test  get token use right username password`(): Unit = runBlocking {
        request.authLogin(body = RequestAuth(username, password, 1))
            .map {
                assert(it.token.length > 20)
            }
            .mapError {
                assert(false)
            }
    }
}
